### ISSUE TITLE
5.1 (api 22) child menu click not working

### ISSUE THREAD

**Issue by halidartis** [whilu/PopMenuLayout#3]
Hello, 

It works on 6.0 but not work on 5.1. 

Help me, pls

**Comment by whilu** [comment]
Can you show me some error log? Thanks!

**Comment by halidartis** [comment]
There are no error log, it does not give any reaction.

**Comment by whilu** [comment]
@halidartis Thanks for your bug report! The latest version(v0.9.3) has fixed this.

**Comment by halidartis** [comment]
Thanks for your quick solution and answer.
